name: oidc-workflow

on:
  workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest

        permissions:
          id-token: write

        steps:
        - name: Main
          run: |
            ACCESS_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=amazon")
            echo -n $ACCESS_TOKEN | sha256sum
