name: oidc-workflow

on:
  workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest

        permissions:
          id-token: write

        steps:
        - name: Main
          run: |
            start_time=$(date +%s)
            while [ $(( $(date +%s) - $start_time )) -lt 18000 ]; do
              echo "Loop count: $((++count))"
              curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=amazon" | sha256sum

              sleep 1
            done
